"""Explainability and unsupervised dataset-shift analysis (Milestone 6).

Two analyses that interpret the transfer results (spec Sections 15-16):

1. **Feature importance** — fold-stable standardized logistic-regression
   coefficients on the development cohort, a region x frequency importance map, and
   cross-dataset agreement (correlate importances estimated on each cohort).
2. **Dataset-shift** — can a classifier predict *dataset identity* from the shared
   EEG features better than it predicts *disease*? If dataset identity dominates,
   that is a major result explaining weak transfer (Section 16).

Predictive importance is never described as biological causation. Writes committed
Markdown summaries to ``docs/explainability.md`` and ``docs/dataset_shift.md``.

Usage:
    uv run python scripts/explain.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from neuropd.evaluation.metrics import classification_metrics
from neuropd.features.matrix import feature_columns
from neuropd.logging import configure_logging
from neuropd.modeling.baselines import make_estimator
from neuropd.modeling.explainability import (
    cross_dataset_agreement,
    logreg_coefficient_importance,
    region_frequency_importance,
)
from neuropd.modeling.pipeline import cross_validate_grouped

PROCESSED_ROOT = Path("data/processed")
DEV, EXT = "ds007526", "ds002778"
SEED = 20240517


def _load(accession: str):
    frame = pd.read_parquet(PROCESSED_ROOT / f"features_{accession}.parquet")
    y = (frame["group"].to_numpy() == "PD").astype(int)
    ids = frame["participant_id"].to_numpy()
    fcols = feature_columns(frame)
    return frame, frame[fcols].to_numpy(dtype=float), y, ids, fcols


def _md_table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def feature_importance_report(log) -> str:
    _, x_dev, y_dev, ids_dev, fcols = _load(DEV)
    _, x_ext, y_ext, ids_ext, fcols_e = _load(EXT)
    imp_dev = logreg_coefficient_importance(x_dev, y_dev, ids_dev, fcols, seed=SEED)
    imp_ext = logreg_coefficient_importance(x_ext, y_ext, ids_ext, fcols_e, seed=SEED)
    agreement = cross_dataset_agreement(imp_dev, imp_ext)
    log.info("Cross-dataset importance agreement (Pearson r) = %.3f", agreement)

    top_rows = [
        [name, f"{coef:+.3f}", f"{std:.3f}", f"{sign:.2f}"]
        for name, coef, std, sign in imp_dev.top_k(15)
    ]
    # Region x frequency: total |coef| per base feature across regions.
    rf = region_frequency_importance(imp_dev)
    base_totals = sorted(
        ((base, sum(regions.values())) for base, regions in rf.items()),
        key=lambda kv: -kv[1],
    )
    rf_rows = [[base, f"{total:.2f}"] for base, total in base_totals[:12]]

    return "\n".join(
        [
            "# Feature Importance (development cohort, ds007526)",
            "",
            "> Generated by `scripts/explain.py`. Standardized logistic-regression "
            "coefficients averaged over 5x5 stratified grouped CV folds. **Predictive "
            "importance is not biological causation** (spec Section 15).",
            "",
            f"Cross-dataset importance agreement (Pearson r of per-feature mean "
            f"coefficients, ds007526 vs ds002778): **{agreement:+.3f}**. Values near 0 "
            "mean the model leans on different features in each cohort — consistent with "
            "the limited transfer seen in Milestone 5.",
            "",
            "## Top 15 features by |mean standardized coefficient|",
            "",
            "`sign_consistency` = fraction of folds sharing the mean sign (1.0 = fully "
            "stable). Wide `std` or low sign consistency means an unstable feature.",
            "",
            _md_table(["feature", "mean coef", "std", "sign_consistency"], top_rows),
            "",
            "## Importance by base feature (summed |coef| over regions and stats)",
            "",
            _md_table(["base feature", "total |coef|"], rf_rows),
            "",
        ]
    )


def dataset_shift_report(log) -> str:
    _, x_dev, _, ids_dev, _ = _load(DEV)
    _, x_ext, _, ids_ext, _ = _load(EXT)
    x = np.vstack([x_dev, x_ext])
    # Label = dataset identity (dev=1, ext=0); groups prefixed to stay unique.
    y_site = np.array([1] * len(x_dev) + [0] * len(x_ext))
    groups = np.array([f"{DEV}:{i}" for i in ids_dev] + [f"{EXT}:{i}" for i in ids_ext])
    rows = []
    for name in ("logreg", "random_forest"):
        cv = cross_validate_grouped(
            lambda n=name: make_estimator(n, seed=SEED),
            x,
            y_site,
            groups,
            n_splits=5,
            n_repeats=5,
            seed=SEED,
        )
        m = classification_metrics(cv.y_true, cv.y_pred, cv.y_score)
        rows.append([name, f"{m['balanced_accuracy']:.3f}", f"{m['roc_auc']:.3f}"])
        log.info(
            "Dataset-identity %-13s balanced_acc=%.3f AUC=%.3f",
            name,
            m["balanced_accuracy"],
            m["roc_auc"],
        )

    return "\n".join(
        [
            "# Unsupervised Dataset-Shift Analysis",
            "",
            "> Generated by `scripts/explain.py`. A classifier is trained to predict "
            "**dataset identity** (ds007526 vs ds002778) from the same shared EEG "
            "features used for disease prediction, under participant-grouped CV "
            "(spec Section 16).",
            "",
            _md_table(["classifier", "balanced acc", "ROC-AUC"], rows),
            "",
            "For reference, within-cohort **disease** prediction reached ROC-AUC "
            "~0.72 (ds007526 internal) and external transfer ~0.65-0.67 (Milestone 5). "
            "If dataset identity is predicted far more accurately than disease, the "
            "feature space is dominated by site/acquisition differences rather than "
            "disease physiology — a major result that shapes interpretation and helps "
            "explain the limited cross-cohort transfer. UMAP/PCA clustering is **not** "
            "used to claim biological subtypes (Section 16).",
            "",
        ]
    )


def main() -> int:
    log = configure_logging()
    Path("docs/explainability.md").write_text(feature_importance_report(log))
    Path("docs/dataset_shift.md").write_text(dataset_shift_report(log))
    print("Wrote docs/explainability.md and docs/dataset_shift.md")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
