"""Generate the committed preprocessing QC / exclusion report (spec Section 10.3).

Reads the per-dataset QC tables written by ``scripts/preprocess.py`` (git-ignored
under ``reports/tables/``) and renders a small, committed Markdown summary to
``docs/preprocessing_qc.md``: per-group clean-epoch and rejection statistics plus
an explicit exclusion table with reasons. Every excluded recording is listed; a
participant is never excluded for weakening model performance (Section 10.3).

Usage:
    uv run python scripts/qc_report.py
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

from neuropd.data.openneuro import DATASETS

TABLES_ROOT = Path("reports/tables")
REPORT = Path("docs/preprocessing_qc.md")


def _md_table(df: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub-flavored Markdown table (no extra deps)."""
    cols = [str(c) for c in df.columns]
    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join("---" for _ in cols) + " |"
    rows = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, sep, *rows])


def _summarize(df: pd.DataFrame) -> pd.DataFrame:
    g = df.groupby("group")
    out = pd.DataFrame(
        {
            "recordings": g.size(),
            "participants": g["participant_id"].nunique(),
            "clean_epochs_median": g["n_epochs_clean"].median().round(1),
            "clean_epochs_min": g["n_epochs_clean"].min(),
            "rejection_rate_mean": g["rejection_rate"].mean().round(3),
            "excluded": g["excluded"].sum(),
        }
    )
    return out.reset_index()


def _render_dataset(accession: str) -> str:
    path = TABLES_ROOT / f"preprocessing_qc_{accession}.csv"
    if not path.is_file():
        return f"## {accession}\n\n_No QC table found ({path}); run preprocess.py._\n"
    df = pd.read_csv(path)
    df["excluded"] = df["excluded"].astype(bool)
    if "session" in df.columns:
        df["session"] = df["session"].fillna("-").replace("", "-")
    lines = [f"## {accession}", ""]
    lines.append(f"- Recordings processed: **{len(df)}**")
    lines.append(f"- Unique participants: **{df['participant_id'].nunique()}**")
    lines.append(f"- Excluded recordings: **{int(df['excluded'].sum())}**")
    lines.append("")
    lines.append(_summarize(df).pipe(_md_table))
    lines.append("")
    excl = df[df["excluded"]]
    if len(excl):
        lines.append("### Excluded recordings")
        lines.append("")
        cols = ["participant_id", "group", "session", "n_epochs_clean", "reasons"]
        lines.append(excl[cols].pipe(_md_table))
    else:
        lines.append(
            "_No recordings excluded: all met the predeclared duration and "
            "clean-epoch minimums (see ADR 0005)._"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    stamp = datetime.now(UTC).isoformat(timespec="seconds")
    header = [
        "# Preprocessing Quality Control",
        "",
        f"> Generated by `scripts/qc_report.py` on {stamp} from the per-dataset QC "
        "tables under `reports/tables/` (git-ignored). Regenerate after running "
        "`scripts/preprocess.py --limit-per-group 0`.",
        "",
        "Exclusion thresholds are predeclared in ADR 0005 (recording < 60 s or "
        "< 20 clean 2 s epochs). Participants are never excluded for weakening model "
        "performance (spec Section 10.3).",
        "",
    ]
    body = [_render_dataset(acc) for acc in DATASETS]
    REPORT.write_text("\n".join(header) + "\n" + "\n".join(body))
    print(f"Wrote {REPORT}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
